export const ActionTypes = {
  SET_JOKES: "SET_JOKES",
  SET_CATEGORY: "SET_CATEGORY",
  SET_SELECTED: "SET_SELECTED",
  SET_LIKE: "SET_LIKE",
  SET_DISLIKE: "SET_DISLIKE",
  SET_SEARCH: "SET_SEARCH",
};
